services:
  db:
    container_name: postgres # -> this is the name of the container
    image: postgres:15.2 # -> this is the name of the image
    environment:
      POSTGRES_USER: felix # -> this is the user of the database
      POSTGRES_PASSWORD: password # -> this is the password of the database
      PGDATA: /data/postgres # -> this is the path of the database
    volumes:
      - postgres:/data/postgres # -> this is the path of the volume
    ports:
      - "5432:5432" # -> this is the port of the container
    networks:
      - postgres # -> this is the network of the container
    restart: unless-stopped # -> this is the restart policy of the container

  customer-api: # -> this is the name of the service
    container_name: customer-api # -> this is the name of the container
    image: felixvjr23/customer-api:latest # -> this is the name of the image
    environment: # -> this is the environment variables
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/customer?user=felix&password=password" # -> this is the url of the database
    ports:
      - "8088:8080" # -> this is the port of the container
    networks:
      - postgres # -> this is the network of the container
    depends_on:
      - db # -> this is the dependency of the container
    restart: unless-stopped # -> this is the restart policy of the container

  customer-react:
    container_name: customer-react
    image: felixvjr23/customer-react:latest
    build:
      context: frontend/client
      args:
        api_base_url: http://localhost:8088
    ports:
      - "3000:5173"
    depends_on:
      - customer-api
    restart: unless-stopped




networks:
  postgres:
    driver: bridge

volumes:
  postgres: