aws:
  s3:
    mock: false

spring:
  datasource:
    url: jdbc:postgresql://awseb-e-dmgnt7mtsq-stack-awsebrdsdatabase-cictgejveylr.ck40tlw5zo9p.us-east-2.rds.amazonaws.com:5432/ebdb
    username: felix
    password: password